config/routes.rb
Rails.application.routes.draw do

  get 'login', to:'sessions#new', as:'login'
  post 'login', to:'sessions#create'
  get 'logout', to:'sessions#destroy', as:'logout'
  get 'alumns/:id/edit_password', to:'alumns#edit_password_alumn', as:'edit_password_alumn'
  put 'alumns/:id/edit_password', to:'alumns#update_password_alumns'
  get 'parents/:id/edit_password', to:'parents#edit_password_parent', as:'edit_password_parent'
  put 'parents/:id/edit_password', to:'parents#update_password_parent'
  get 'employees/:id/edit_password', to:'employees#edit_password_employee', as:'edit_password_employee'
  put 'employees/:id/edit_password', to:'employees#update_password_employee'
  get 'classrooms/:id/add_alumns', to:'classrooms#add_alumns', as:'add_alumns'
  post 'classrooms/:id/add_alumns', to:'classrooms#add_alumn', as:'add_alumn'

  get '/errors/error_500' , to:'errors#error_500'
  match "/500", :to => "errors#error_500", :via => :all

  get 'subjects/:id/add_classrooms', to:'subjects#add_classrooms', as:'add_classrooms'
  post 'subjects/:id/add_classrooms', to:'subjects#add_classroom', as:'add_classroom'
  get 'subjects/:id/show_subjects', to:'subjects#show_subjects', as:'show_subjects'


  get 'classroom/:id/classroom_subjects', to:'subjects#classroom_subjects', as:'classroom_subjects'

  get 'classroom/:id/subject/:subject_id/grades', to:'grades#set_grades', as:'set_grades'
  put 'classroom/:id/subject/:subject_id/grades', to:'grades#post_grades', as:'post_grades'


  get 'classroom/:id/subject/:subject_id/grade/:grade_id/history', to:'grade_histories#show_history', as:'show_history'

  root 'sessions#new'

  get 'teachers/:id/teacher_classrooms', to:'teachers#teacher_classrooms', as:'teacher_classrooms'
  get 'teachers/:teacher_id/teacher_classroom_subjects/:classroom_id', to:'teachers#teacher_classroom_subjects',
       as:'teacher_classroom_subjects'

  get 'teachers/:teacher_id/teacher_classroom_subjects/:classroom_id/teacher_grades/:subject_id', to:'teachers#teacher_grades',
       as:'teacher_grades'


  get '/alumns/:id/report', to: 'alumns#report', as: 'alumn_report'

  get '/login_helper', to: 'sessions#login_helper', as: 'login_helper'
  get '/reader/index' , to: 'reader#index'

  namespace :api, defaults: { format: :json } do
    resources :alumns
    resources :strikes
    resources :suspensions
    resources :notifications
    resources :parents
  end


  root 'sessions#new'

  resources :users
  resources :alumns do
    resources :strikes
  end
  resources :strikes
  resources :parents
  resources :notifications
  resources :secretaries
  resources :employees
  resources :teachers
  resources :classrooms
  resources :suspensions
  resources :grades
  resources :subjects
  resources :school_misses
  resources :principal, only: [:show, :edit, :update]
  resources :alumns do
    resources :school_misses
  end

  resources :parents do
    resources :alumns
  end

  resources :alumns do
    resources :suspensions
  end

  resources :classrooms do
    resources :subjects
  end

  resources :classrooms do
    resources :grades
  end
end

app/models/principal.rb
#File name: principal.rb
#Class name: Principal
#Description: Validates principal's attributes outside single table inheritance
class Principal < Employee
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  include SessionsHelper

  def show
    if ( is_principal? )
      @principal = Employee.find(params[:id])
    end
  end

  def edit
    if ( is_principal? )
      @principal = Employee.find(params[:id])
    end
  end

  def update
    if ( is_principal? )
      @principal = Employee.find(params[:id])
      if ( @principal.update(principal_params) )
        flash[:notice] = "Diretor(a) alterado(a) com sucesso"
        redirect_to @principal
      else
        render 'edit'
      end
    end
  end

private
  def principal_params
    params.require(:principal).permit(:registry,
																			:admission_date,
																			:employee_cpf,
																			:password,
																			:name,
																			:phone,
																			:gender,
																			:birth_date)

  	end
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/principal/_form.html.erb
<%= form_for (@principal) do |f| %>
  <% if @principal.errors.any? %>
    <div class="container">
      <div class="text-danger text-justify">
        <div id="error_explanation">
          <h2 class=""><%= pluralize(@principal.errors.count, "erro") %> proibiram este formulario de ser salvo:</h2>
          <ul>
          <% @principal.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-user"></span>
         Nome
      </span>
      <%= f.text_field :name, class:"form-control", placeholder:"Nome do usuário" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :registry, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-id-badge"></span>
        Matrícula
      </span>
      <%= f.number_field :registry, class:"form-control", placeholder:"Ex.: 153456" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :employee_cpf, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-id-badge"></span>
        CPF
      </span>
      <%= f.text_field :employee_cpf, class:"form-control", placeholder:"Ex.: 99999999999" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :phone, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-phone"></span>
         Telefone
      </span>
      <%= f.text_field :phone, class:"form-control", placeholder:'Somente números com DDD.' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :birth_date, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-gift"></span>
         Data de nascimento
      </span>
      <%= f.date_field :birth_date, class:"form-control", placeholder:"Ex.: dd/mm/aaaa" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :admission_date, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-calendar"></span>
         Admissão
      </span>
      <%= f.date_field :admission_date, class:"form-control", placeholder:"Ex.: dd/mm/aaaa" %>
    </div>
  </div>

  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-venus-mars"></span>
         Sexo
      </span>
      <div class="btn-group" data-toggle="buttons">
        <label class="btn btn-radio">
          <%= f.radio_button(:gender,"Feminino") %> Feminino
        </label>
        <label class="btn btn-radio">
          <%= f.radio_button(:gender,"Masculino") %> Masculino
        </label>
      </div>
    </div>
  </div>
  <%= f.hidden_field :permission, :value => "Principal"%>
  <%= f.button '<span class="fa fa-check"></span> Salvar'.html_safe, type:"submit", class:'btn btn-lg btn-success' %>
  <%= link_to '<span class="fa fa-arrow-left"></span> Voltar'.html_safe, principal_path(@principal), class:'btn btn-lg btn-warning' %>
<% end %>

app/views/principal/edit.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-style">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#coll-nav" aria-expanded="false">
        <span class="fa fa-angle-down"></span>
      </button>
      <% if is_alumn? %>
        <%= link_to image_tag("Logo_Escola_X_50x50.png", :alt => "logo"), alumn_path(@current_user) %>
      <% elsif is_parent? %>
        <%= link_to image_tag("Logo_Escola_X_50x50.png", :alt => "logo"), alumns_path %>
      <% elsif is_teacher? %>
        <%= link_to image_tag("Logo_Escola_X_50x50.png", :alt => "logo"), teacher_path(@current_user) %>
      <% else %>
        <%= link_to image_tag("Logo_Escola_X_50x50.png", :alt => "logo"), users_path %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="coll-nav">
      <ul class="nav navbar-nav">
          <% if is_teacher? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-hospopup="true" aria-expanded="false">
                <span class="fa fa-plus"></span> Criar
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to '<span class="fa fa-paper-plane-o"></span> Criar Notificação'.html_safe, new_notification_path %></li>
              </ul>
            </li>
          <%end%>
          <% if is_principal? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-hospopup="true" aria-expanded="false">
                <span class="fa fa-plus"></span> Criar
              </a>
              <ul class="dropdown-menu">
                <li><%=link_to '<span class="fa fa-book"></span> Criar Matéria'.html_safe, subjects_path %></li>
                <%if is_principal? %>
                  <li><%= link_to '<span class="fa fa-user-plus"></span> Criar Responsável e Aluno'.html_safe, new_parent_path %></li>
                  <li><%= link_to '<span class="fa fa-user-circle-o"></span> Criar Secretário'.html_safe, new_secretary_path %></li>
                  <li><%= link_to '<span class="fa fa-user-plus"></span> Criar Professor'.html_safe, new_teacher_path %></li>
                  <li><%= link_to '<span class="fa fa-users"></span> Criar Turma'.html_safe, new_classroom_path %></li>
                  <li><%= link_to '<span class="fa fa-paper-plane-o"></span> Criar Notificação'.html_safe, new_notification_path %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        <%if is_principal? or is_secretary? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-hospopup="true" aria-expanded="false">
              <span class="fa fa-search"></span> Visualizar
            </a>
            <ul class="dropdown-menu">
              <% if is_principal? %>
                <li><%= link_to '<span class="fa fa-user-circle-o"></span> Secretários'.html_safe, secretaries_path %></li>
                <li><%=link_to '<span class="fa fa-book"></span> Matéria'.html_safe, subjects_path %></li>
              <% end %>
              <li><%= link_to '<span class="fa fa-users"></span> Turmas'.html_safe, classrooms_path %></li>
              <li><%= link_to '<span class="fa fa-user"></span> Alunos'.html_safe, alumns_path %></li>
              <li><%= link_to '<span class="fa fa-user-circle"></span> Responsáveis'.html_safe, parents_path %></li>
            </ul>
          </li>
        <% end %>
        <li><%=link_to '<span class="fa fa-sticky-note-o"></span> Avisos'.html_safe, notifications_path %></li>
        <li><%=link_to '<span class="fa fa-sign-out"></span> Sair'.html_safe, logout_path %></li>
      </ul>
    </div>
  </div>
</nav>

<section class="content-section" id="create">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h1 class="text-uppercase text-center">
          <span class="fa fa-edit"></span> editar diretor
        </h1>
        <%= render 'principal/form' %>
      </div>
    </div>
  </div>
</section>

app/views/principal/show.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-style">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#coll-nav" aria-expanded="false">
        <span class="fa fa-angle-down"></span>
      </button>
      <%= link_to image_tag("Logo_Escola_X_50x50.png", :alt => "logo"), users_path %>
    </div>
    <div class="collapse navbar-collapse" id="coll-nav">
      <ul class="nav navbar-nav">
          <% if is_teacher? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-hospopup="true" aria-expanded="false">
                <span class="fa fa-plus"></span> Criar
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to '<span class="fa fa-paper-plane-o"></span> Criar Notificação'.html_safe, new_notification_path %></li>
              </ul>
            </li>
          <%end%>
          <% if is_principal? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-hospopup="true" aria-expanded="false">
                <span class="fa fa-plus"></span> Criar
              </a>
              <ul class="dropdown-menu">
                <li><%=link_to '<span class="fa fa-book"></span> Criar Matéria'.html_safe, subjects_path %></li>
                <%if is_principal? %>
                  <li><%= link_to '<span class="fa fa-user-plus"></span> Criar Responsável e Aluno'.html_safe, new_parent_path %></li>
                  <li><%= link_to '<span class="fa fa-user-circle-o"></span> Criar Secretário'.html_safe, new_secretary_path %></li>
                  <li><%= link_to '<span class="fa fa-user-plus"></span> Criar Professor'.html_safe, new_teacher_path %></li>
                  <li><%= link_to '<span class="fa fa-users"></span> Criar Turma'.html_safe, new_classroom_path %></li>
                  <li><%= link_to '<span class="fa fa-paper-plane-o"></span> Criar Notificação'.html_safe, new_notification_path %></li>
                <% end %>
              </ul>
            </li>
          <% end %>
        <%if is_principal? or is_secretary? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-hospopup="true" aria-expanded="false">
              <span class="fa fa-search"></span> Visualizar
            </a>
            <ul class="dropdown-menu">
              <% if is_principal? %>
                <li><%= link_to '<span class="fa fa-user-circle-o"></span> Secretários'.html_safe, secretaries_path %></li>
                <li><%=link_to '<span class="fa fa-book"></span> Matéria'.html_safe, subjects_path %></li>
              <% end %>
              <li><%= link_to '<span class="fa fa-users"></span> Turmas'.html_safe, classrooms_path %></li>
              <li><%= link_to '<span class="fa fa-user"></span> Alunos'.html_safe, alumns_path %></li>
              <li><%= link_to '<span class="fa fa-user-circle"></span> Responsáveis'.html_safe, parents_path %></li>
            </ul>
          </li>
        <% end %>
        <li><%=link_to '<span class="fa fa-sticky-note-o"></span> Avisos'.html_safe, notifications_path %></li>
        <li><%=link_to '<span class="fa fa-sign-out"></span> Sair'.html_safe, logout_path %></li>
      </ul>
    </div>
  </div>
</nav>
<% if flash[:notice]%>
<br>
<br>
 <div class="alert alert-warning" role = "alert"><%= flash[:notice]%></div>
<% end %>
<section class="content-section" id="alumns-desc">

  <div class="container">
    <div class="pull-right">
      <%= link_to '<span class="fa fa-arrow-left"></span> Voltar'.html_safe, users_path, class:'btn btn-sm btn-crown-of-thorns' %>
      <%if is_principal? %>
        <%= link_to '<span class="fa fa-edit"></span> Editar'.html_safe, edit_principal_path(@principal), class:"btn btn-sm btn-default" %>
        <%= link_to '<span class="fa fa-edit"></span> Editar Senha'.html_safe, edit_password_employee_path(@principal), class:"btn btn-sm btn-default" %>
      <%end%>
    </div>
    <div class="row item">
      <div class="col-sm-12 col-md-4">
        <%= image_tag("avatar_250x300.png", alt: "", class: "img-responsive" ) %>
      </div>
      <div class="col-sm-12 col-md-8 text-capitalize descript">
        <h3>Nome: <%= @principal.name %></h3>
        <h4>Telefone: <%= @principal.phone %></h4>
        <h4>Sexo: <%= @principal.gender %></h4>
        <h4>Endereço: <%= @principal.address %></h4>
        <h4>Matrícula: <%= @principal.registry %></h4>
        <h4>CPF: <%= @principal.employee_cpf %></h4>
        <h4>Data de Nascimento: <%= @principal.birth_date.strftime('%d/%m/%Y') %></h4>
        <h4>Admissão: <%= @principal.admission_date.strftime('%d/%m/%Y') %></h4>
      </div>
    </div>
  </div>
</section>