config/routes.rb
Rails.application.routes.draw do

  get 'login', to:'sessions#new', as:'login'
  post 'login', to:'sessions#create'
  get 'logout', to:'sessions#destroy', as:'logout'
  get 'alumns/:id/edit_password', to:'alumns#edit_password_alumn', as:'edit_password_alumn'
  put 'alumns/:id/edit_password', to:'alumns#update_password_alumns'
  get 'parents/:id/edit_password', to:'parents#edit_password_parent', as:'edit_password_parent'
  put 'parents/:id/edit_password', to:'parents#update_password_parent'
  get 'employees/:id/edit_password', to:'employees#edit_password_employee', as:'edit_password_employee'
  put 'employees/:id/edit_password', to:'employees#update_password_employee'
  get 'classrooms/:id/add_alumns', to:'classrooms#add_alumns', as:'add_alumns'
  post 'classrooms/:id/add_alumns', to:'classrooms#add_alumn', as:'add_alumn'

  get '/errors/error_500' , to:'errors#error_500'
  match "/500", :to => "errors#error_500", :via => :all

  get 'subjects/:id/add_classrooms', to:'subjects#add_classrooms', as:'add_classrooms'
  post 'subjects/:id/add_classrooms', to:'subjects#add_classroom', as:'add_classroom'
  get 'subjects/:id/show_subjects', to:'subjects#show_subjects', as:'show_subjects'


  get 'classroom/:id/classroom_subjects', to:'subjects#classroom_subjects', as:'classroom_subjects'

  get 'classroom/:id/subject/:subject_id/grades', to:'grades#set_grades', as:'set_grades'
  put 'classroom/:id/subject/:subject_id/grades', to:'grades#post_grades', as:'post_grades'


  get 'classroom/:id/subject/:subject_id/grade/:grade_id/history', to:'grade_histories#show_history', as:'show_history'

  root 'sessions#new'

  get 'teachers/:id/teacher_classrooms', to:'teachers#teacher_classrooms', as:'teacher_classrooms'
  get 'teachers/:teacher_id/teacher_classroom_subjects/:classroom_id', to:'teachers#teacher_classroom_subjects',
       as:'teacher_classroom_subjects'

  get 'teachers/:teacher_id/teacher_classroom_subjects/:classroom_id/teacher_grades/:subject_id', to:'teachers#teacher_grades',
       as:'teacher_grades'


  get '/alumns/:id/report', to: 'alumns#report', as: 'alumn_report'

  get '/login_helper', to: 'sessions#login_helper', as: 'login_helper'
  get '/reader/index' , to: 'reader#index'

  namespace :api, defaults: { format: :json } do
    resources :alumns
    resources :strikes
    resources :suspensions
    resources :notifications
    resources :parents
  end


  root 'sessions#new'

  resources :users
  resources :alumns do
    resources :strikes
  end
  resources :strikes
  resources :parents
  resources :notifications
  resources :secretaries
  resources :employees
  resources :teachers
  resources :classrooms
  resources :suspensions
  resources :grades
  resources :subjects
  resources :school_misses
  resources :principal, only: [:show, :edit, :update]
  resources :alumns do
    resources :school_misses
  end

  resources :parents do
    resources :alumns
  end

  resources :alumns do
    resources :suspensions
  end

  resources :classrooms do
    resources :subjects
  end

  resources :classrooms do
    resources :grades
  end
end

app/controllers/users_controller.rb
# File name: users_controller.rb
# Class name: UsersController
# Description: Controller used to making sense of the request users
class UsersController < ApplicationController
  include SessionsHelper

  def index
    if ( is_employee? )
      @alumns = Alumn.all
      @employees = Employee.all
      @parents = Parent.all
    else
      redirect_to "/errors/error_500"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_password.html.erb
<%= render 'layouts/navbar' %>
<section class="content-section" id="alumns-desc">
  <div class="container">
    <div class="col-xs-8 col-xs-offset-2">
      <h1 class="text-capitalize text-center">Resetar senha</h1>
      <%= form_for @user do |user| %>
      <div class="form-group">
        <h2 class="text-left text-capitalize"><%= @user.name %></h2>
        <%= user.label :password, class:'text-muted text-uppercase' %>
        <div class="input-group">
          <span class="input-group-addon fa fa-unlock"></span>
          <%= user.password_field :password, class:'form-control', placeholder:'Insira a nova senha.' %>
        </div>
      </div>
        <%= user.submit "Salvar",class:'btn btn-lg btn-success' %>
        <%= link_to '<span class="fa fa-arrow-left"></span> Voltar'.html_safe, users_path, class:'btn btn-lg btn-default' %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<%= render "layouts/navbar" %>
<% if flash[:alert]%>
  <br>
  <br>
 <div class="alert alert-danger" role = "alert"><%= flash[:alert]%></div>
<% end %>
<% if flash[:success]%>
 <div class="alert alert-success" role = "alert"><%= flash[:success]%></div>
<% end %>
<h1 class="text-uppercase text-center" id="title-list"><span></span></h1>
<section class="content-section" id="alumns-list">
  <div class="container">
    <% if ( is_principal? ) %>
    <section id="hub" class="text-center">
      <h3 class="text-muted text-center">
        Olá, Diretor!<br>
        <small class="visible-md visible-lg">Coloque o mouse para exibir opções</small>
        <small class="visible-sm visible-xs">Menu de acesso rápido</small>
      </h3>
      <div class="" id="hub-grid">
        <div class="row">
          <div class="col-xs-12 col-md-3 hub-item">
            <%= link_to '<span class="fa fa-user"></span> Alunos'.html_safe, alumns_path, class:"btn btn-block btn-lg btn-success" %>
          </div>
          <div class="col-xs-12 col-md-3 hub-item">
            <%= link_to '<span class="fa fa-user-circle-o"></span> Responsáveis'.html_safe, parents_path, class:"btn btn-block btn-lg btn-warning" %>
          </div>
          <div class="col-xs-12 col-md-3 hub-item">
            <%= link_to '<span class="fa fa-id-card"></span> Funcionários'.html_safe, employees_path, class:"btn btn-block btn-lg btn-info" %>
          </div>
          <div class="col-xs-12 col-md-3 hub-item">
            <%= link_to '<span class="fa fa-sticky-note"></span> Avisos'.html_safe, notifications_path, class:"btn btn-block btn-lg btn-purple" %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-md-4 hub-item">
            <%= link_to '<span class="fa fa-users"></span> Turmas'.html_safe, classrooms_path, class:"btn btn-block btn-lg btn-crown-of-thorns" %>
          </div>
          <div class="col-xs-12 col-md-4 hub-item">
            <%= link_to '<span class="fa fa-book"></span> Matérias'.html_safe, subjects_path, class:"btn btn-block btn-lg btn-jacarta" %>
          </div>
          <div class="col-xs-12 col-md-4 hub-item">
            <%= link_to '<span class="fa fa-graduation-cap"></span> Professores'.html_safe, teachers_path, class:"btn btn-block btn-lg btn-mojo" %>
          </div>
        </div>
      </div>
    </section>
    <% end %>
  </div>
</section>