config/routes.rb
Rails.application.routes.draw do

  get 'login', to:'sessions#new', as:'login'
  post 'login', to:'sessions#create'
  get 'logout', to:'sessions#destroy', as:'logout'
  get 'alumns/:id/edit_password', to:'alumns#edit_password_alumn', as:'edit_password_alumn'
  put 'alumns/:id/edit_password', to:'alumns#update_password_alumns'
  get 'parents/:id/edit_password', to:'parents#edit_password_parent', as:'edit_password_parent'
  put 'parents/:id/edit_password', to:'parents#update_password_parent'
  get 'employees/:id/edit_password', to:'employees#edit_password_employee', as:'edit_password_employee'
  put 'employees/:id/edit_password', to:'employees#update_password_employee'
  get 'classrooms/:id/add_alumns', to:'classrooms#add_alumns', as:'add_alumns'
  post 'classrooms/:id/add_alumns', to:'classrooms#add_alumn', as:'add_alumn'

  get '/errors/error_500' , to:'errors#error_500'
  match "/500", :to => "errors#error_500", :via => :all

  get 'subjects/:id/add_classrooms', to:'subjects#add_classrooms', as:'add_classrooms'
  post 'subjects/:id/add_classrooms', to:'subjects#add_classroom', as:'add_classroom'
  get 'subjects/:id/show_subjects', to:'subjects#show_subjects', as:'show_subjects'


  get 'classroom/:id/classroom_subjects', to:'subjects#classroom_subjects', as:'classroom_subjects'

  get 'classroom/:id/subject/:subject_id/grades', to:'grades#set_grades', as:'set_grades'
  put 'classroom/:id/subject/:subject_id/grades', to:'grades#post_grades', as:'post_grades'


  get 'classroom/:id/subject/:subject_id/grade/:grade_id/history', to:'grade_histories#show_history', as:'show_history'

  root 'sessions#new'

  get 'teachers/:id/teacher_classrooms', to:'teachers#teacher_classrooms', as:'teacher_classrooms'
  get 'teachers/:teacher_id/teacher_classroom_subjects/:classroom_id', to:'teachers#teacher_classroom_subjects',
       as:'teacher_classroom_subjects'

  get 'teachers/:teacher_id/teacher_classroom_subjects/:classroom_id/teacher_grades/:subject_id', to:'teachers#teacher_grades',
       as:'teacher_grades'


  get '/alumns/:id/report', to: 'alumns#report', as: 'alumn_report'

  get '/login_helper', to: 'sessions#login_helper', as: 'login_helper'
  get '/reader/index' , to: 'reader#index'

  namespace :api, defaults: { format: :json } do
    resources :alumns
    resources :strikes
    resources :suspensions
    resources :notifications
    resources :parents
  end


  root 'sessions#new'

  resources :users
  resources :alumns do
    resources :strikes
  end
  resources :strikes
  resources :parents
  resources :notifications
  resources :secretaries
  resources :employees
  resources :teachers
  resources :classrooms
  resources :suspensions
  resources :grades
  resources :subjects
  resources :school_misses
  resources :principal, only: [:show, :edit, :update]
  resources :alumns do
    resources :school_misses
  end

  resources :parents do
    resources :alumns
  end

  resources :alumns do
    resources :suspensions
  end

  resources :classrooms do
    resources :subjects
  end

  resources :classrooms do
    resources :grades
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
	belongs_to :teacher
	has_many :grades, dependent: :destroy
	has_many :classroom_subjects, dependent: :destroy
	has_many :alumns, through: :grades
	has_many :classrooms, through: :classroom_subjects
	belongs_to :classroom_grade
	validates_associated :grades
	validates_associated :alumns

  validates :name_subject,
  			presence: { message: "Não pode estar em branco!" },
  			length: { minimum: 5,
		            maximum: 20,
		            :too_short => "deve possuir mais de 5 caracteres.",
		            :too_long => "deve possuir no máximo 20 caracteres."}


  validates :teacher,
            presence: { message: "não válido para criar matéria!" },
            uniqueness: true

end

app/controllers/subjects_controller.rb
# File name: subjects_controller.rb
# Class name: SubjectsController
# Description: Controller used to communicate with the proprietary view of subjects
class SubjectsController < ApplicationController
	include SessionsHelper

  def index
  	if ( is_principal? or is_teacher? )
  		@subjects = Subject.all
    else
      redirect_to "/errors/error_500"
  	end
  end

	def classroom_subjects
		@classroom = Classroom.find(params[:id])
		@subjects = @classroom.subjects
	end

  def new
  	if ( is_principal? )
			@classroom_grades = ClassroomGrade.all
  		@subject = Subject.new
    else
      redirect_to "/errors/error_500"
  	end
  end

  def edit
  	if ( is_principal? )
			@classroom_grades = ClassroomGrade.all
    	@subject = Subject.find(params[:id])
    else
      redirect_to "/errors/error_500"
    end
  end

  def show
  	if( is_principal? )
  		@subject = Subject.find(params[:id])
    else
      redirect_to "/errors/error_500"
  	end
  end

  def create
  	if ( is_principal? )
			@classroom_grades = ClassroomGrade.all
			@subject = Subject.new(subject_params)
			@teacher = Teacher.find_by_registry(params[:teacher_registry])
			if ( @teacher.nil? )
				@subject.save
				render 'new'
			else
				@subject.teacher_id = @teacher.id
	  		if ( @subject.save )
					flash[:success] = "Matéria criada com sucesso"
	    		redirect_to @subject
	    	else
	    		render 'new'
	    	end
	    end
    else
      redirect_to "/errors/error_500"
		end
  end

  def destroy
  	if ( is_principal? )
  		@subject = Subject.find(params[:id])
  		@subject.destroy
			flash[:alert] = "Matéria excluída com sucesso"
  		redirect_to subjects_path
    else
      redirect_to "/errors/error_500"
  	end
  end

  def update
  	if ( is_principal? )
			@classroom_grades = ClassroomGrade.all
			@subject = Subject.find(params[:id])
			@teacher = Teacher.find_by_registry(params[:teacher_registry])
			if ( @teacher.nil? )
				@subject.update(subject_params)
				render 'edit'
			else
				@subject.teacher_id = @teacher.id
	  		if ( @subject.update(subject_params) )
					flash[:notice] = "Matéria alterada com sucesso"
	    		redirect_to @subject
	    	else
	    		render 'edit'
	    	end
	    end
    else
      redirect_to "/errors/error_500"
		end
  end

  def add_classrooms
    if ( is_principal? )
      @classroom = Classroom.find(params[:id])
      @subjects = Subject.all
    end
  end

  def add_classroom
    if ( is_principal? )
      @classroom = Classroom.find(params[:id])
      @subject = Subject.find(params[:subject_id])
			if !((ClassroomSubject.where(classroom_id: @classroom.id).where(subject_id: @subject.id)).exists?)
				@classroom_subject = ClassroomSubject.new
				@classroom_subject.subject_id = @subject.id
				@classroom_subject.classroom_id = @classroom.id
				if @classroom_subject.save
					flash[:success] = "Matéria adicionada com sucesso"
					redirect_to add_classrooms_path(@classroom)
				end
			else
				flash[:alert] = "Matéria não pode ser adicionada ou já existe na turma"
				redirect_to add_classrooms_path(@classroom)
			end
    end
  end

  def show_subjects
    @classroom = Classroom.find(params[:id])
    @subjects = @classroom.subject
  end

  private
  def subject_params
  	params.require(:subject).permit(:name_subject,
		:class_level,:teacher_id,:classroom_id,:subject_id, :classroom_grade_id)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= render "layouts/navbar" %>
<%= form_for (@subject)  do |f| %>
  <% if @subject.errors.any? %>
    <div class="container">
      <div class="text-danger text-justify">
        <div id="error_explanation">
          <h2 class=""><%= pluralize(@subject.errors.count, "erro") %> proibiram este formulario de ser salvo:</h2>
          <ul>
          <% @subject.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name_subject, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-user"></span>
         Nome
      </span>
      <%= f.text_field :name_subject, class:"form-control", placeholder:"Nome da matéria" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :classroom_id, class:"sr-only", id: "sel1" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-television"></span>
        Série
      </span>
      <%= f.select :classroom_grade_id, @classroom_grades.collect {|classroom_grade| [classroom_grade.name_classroom_grade, classroom_grade.id]}, {:include_blank => false}, {:class => "form-control", :id => "sel1"}%>
    </div>
  </div>
  <div class="form-group">

    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-gift"></span>
         Matrícula do Professor
      </span>
      <%= text_field_tag('teacher_registry', nil, placeholder: "123456", class: "form-control") %>
    </div>
  </div>
  <%= f.button '<span class="fa fa-check"></span> Salvar'.html_safe, type:"submit", class:'btn btn-lg btn-success' %>

<% end %>

app/views/subjects/add_classrooms.html.erb
<%= render "layouts/navbar" %>

<% if flash[:success]%>
<br>
<br>
<div class="alert alert-success" role = "alert"><%= flash[:success]%></div>
<% end %>
<% if flash[:alert]%>
<br>
<br>
 <div class="alert alert-danger" role = "alert"><%= flash[:alert]%></div>
<% end %>
<h1 class="text-uppercase text-center" id="title-list"><span class="fa fa-sticky-note text-left"></span> Lista de Matérias</h1>
<hr>
<section class="content-section" >
  <div class="container">
    <% @subjects.each do |subject| %>
      <div class="row item">
        <div class="col-sm-12 col-md-8 text-capitalize descript">
          <h3>Matéria: <%= subject.name_subject %></h3>
          <h4>Série: <%= subject.class_level %></h4>
          <h4>Professor Responsável: <%=subject.teacher.name %></h4>
          <%= link_to '<span class="fa fa-search-plus"></span> Mostrar'.html_safe, subject_path(subject), class:"btn btn-default" %>
          <%= link_to '<span class="fa fa-check"></span> Adicionar Matéria'.html_safe, add_classroom_path(subject_id: subject.id) ,method: :post, class:'btn btn-default btn-success' %>
        </div>
      </div>
    <%end%>
  </div>
</section>

app/views/subjects/classroom_subjects.html.erb
<%= render "layouts/navbar" %>
<h1 class="text-uppercase text-center" id="title-list"><span class="fa fa-sticky-note text-left"></span> Matérias</h1>
<hr>
<section class="content-section" >
  <div class="container">
    <div class="pull-right">
      <%= link_to '<span class="fa fa-address-card"></span> Adicionar Matérias'.html_safe, add_classroom_path(@classroom), class:'btn btn-sm btn-warning' %>
    </div>
    <% @subjects.each do |subject| %>
      <div class="row item">
        <div class="col-sm-12 col-md-8 text-capitalize descript">
          <h3>Matéria: <%= subject.name_subject %></h3>
          <h4>Série: <%= subject.class_level %></h4>
          <h4>Professor Responsável: <%=subject.teacher.name %></h4>
          <%= link_to '<span class="fa fa-search-plus"></span> Mostrar'.html_safe, subject_path(subject), class:"btn btn-default" %>
          <%= link_to '<span class="fa fa-search-plus"></span> Notas'.html_safe, set_grades_path(subject_id: subject), class:"btn btn-success" %>
        </div>
      </div>
    <%end%>
  </div>
</section>

app/views/subjects/edit.html.erb
<%= render "layouts/navbar" %>
<section class="content-section" id="create">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <h1 class="text-center text-uppercase">
          <span class="fa fa-refresh"></span> Alterar Matéria
        </h1>
        <%= render 'subjects/form' %>
      </div>
    </div>
  </div>
</section>

app/views/subjects/index.html.erb
<%= render "layouts/navbar" %>
<% if flash[:alert]%>
<br>
<br>
 <div class="alert alert-danger" role = "alert"><%= flash[:alert]%></div>
<% end %>
<h1 class="text-uppercase text-center" id="title-list"><span class="fa fa-sticky-note text-left"></span> Matérias</h1>
<hr>
<section class="content-section" >
  <div class="container">
    <% if is_principal? %>
      <%= link_to '<span class="fa fa-plus-circle"></span> Nova Matéria'.html_safe, new_subject_path, class:"text-center btn btn-info" %>
    <% end %>
    <% @subjects.each do |subject| %>
      <div class="row item">
        <div class="col-sm-12 col-md-8 text-capitalize">
          <h3>Matéria: <%= subject.name_subject %></h3>
          <h4>Série: <%= subject.class_level %></h4>
          <h4>Professor Responsável: <%=subject.teacher.name %></h4>
          <%= link_to '<span class="fa fa-search-plus"></span> Mostrar'.html_safe, subject_path(subject), class:"btn btn-default" %>
        </div>
      </div>
    <%end%>
  </div>
</section>

app/views/subjects/new.html.erb
<%= render "layouts/navbar" %>
<section class="content-section" id="create">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <h1 class="text-center text-uppercase">
          <span class="fa fa-user-plus"></span> Criar Matéria
        </h1>
        <%= render 'subjects/form' %>
      </div>
    </div>
  </div>
</section>

app/views/subjects/show.html.erb
<%= render "layouts/navbar" %>
<br>
<br>
 <% if flash[:success]%>
  <div class="alert alert-success" role = "alert"><%= flash[:success]%></div>
 <% end %>
 <% if flash[:notice]%>
  <div class="alert alert-warning" role = "alert"><%= flash[:notice]%></div>
 <% end %>
<section class="content-section" id="alumns-desc">
  <div class="container">
    <div class="pull-right">
      <%if @current_user.permission=="Principal" %>
        <%= link_to '<span class="fa fa-edit"></span> Editar'.html_safe, edit_subject_path(@subject), class:"btn btn-sm btn-default" %>
        <%= link_to '<span class="fa fa-times"></span> Excluir'.html_safe, "", method: :delete, class:'btn btn-sm btn-danger', data: { confirm: 'Tem certeza? Essa alteração não pode ser desfeita.' }, name:"delete" %>
      <%end%>
    </div>
      <div class="row item">
        <div class="col-sm-12 col-md-8 text-capitalize descript">
          <h3>Matéria: <%= @subject.name_subject %></h3>
          <h4>Série: <%= @subject.class_level %></h4>
          <h4><%=link_to "Professor: #{@subject.teacher.name}",teacher_path(@subject.teacher), class: "btn btn-default" %></h4>
        </div>
    </div>
  </div>
</section>

app/views/subjects/show_subjects.html.erb
<%= render "layouts/navbar" %>
<h1 class="text-uppercase text-center" id="title-list"><span class="fa fa-sticky-note text-left"></span> Matérias</h1>
<hr>
<section class="content-section" >
  <div class="container">
 
  <% if is_principal? %>
    <%= link_to '<span class="fa fa-plus-circle"></span> Nova Matéria'.html_safe, new_subject_path, class:"text-center btn btn-info" %>
  <% end %>
      
  <% @subjects.each do |subject| %>
      <div class="row item">
        <div class="col-sm-12 col-md-8 text-capitalize descript">
          <h3>Matéria: <%= subject.name_subject %></h3>
          <h4>Série: <%= subject.class_level %></h4>
          <h4>Professor Responsável: <%=subject.teacher.name %></h4>
          <%= link_to '<span class="fa fa-search-plus"></span> Mostrar'.html_safe, subject_path(subject), class:"btn btn-default" %>
        </div>
      </div>
    <%end%>
  </div>
</section>