config/routes.rb
Rails.application.routes.draw do

  get 'login', to:'sessions#new', as:'login'
  post 'login', to:'sessions#create'
  get 'logout', to:'sessions#destroy', as:'logout'
  get 'alumns/:id/edit_password', to:'alumns#edit_password_alumn', as:'edit_password_alumn'
  put 'alumns/:id/edit_password', to:'alumns#update_password_alumns'
  get 'parents/:id/edit_password', to:'parents#edit_password_parent', as:'edit_password_parent'
  put 'parents/:id/edit_password', to:'parents#update_password_parent'
  get 'employees/:id/edit_password', to:'employees#edit_password_employee', as:'edit_password_employee'
  put 'employees/:id/edit_password', to:'employees#update_password_employee'
  get 'classrooms/:id/add_alumns', to:'classrooms#add_alumns', as:'add_alumns'
  post 'classrooms/:id/add_alumns', to:'classrooms#add_alumn', as:'add_alumn'

  get '/errors/error_500' , to:'errors#error_500'
  match "/500", :to => "errors#error_500", :via => :all

  get 'subjects/:id/add_classrooms', to:'subjects#add_classrooms', as:'add_classrooms'
  post 'subjects/:id/add_classrooms', to:'subjects#add_classroom', as:'add_classroom'
  get 'subjects/:id/show_subjects', to:'subjects#show_subjects', as:'show_subjects'


  get 'classroom/:id/classroom_subjects', to:'subjects#classroom_subjects', as:'classroom_subjects'

  get 'classroom/:id/subject/:subject_id/grades', to:'grades#set_grades', as:'set_grades'
  put 'classroom/:id/subject/:subject_id/grades', to:'grades#post_grades', as:'post_grades'


  get 'classroom/:id/subject/:subject_id/grade/:grade_id/history', to:'grade_histories#show_history', as:'show_history'

  root 'sessions#new'

  get 'teachers/:id/teacher_classrooms', to:'teachers#teacher_classrooms', as:'teacher_classrooms'
  get 'teachers/:teacher_id/teacher_classroom_subjects/:classroom_id', to:'teachers#teacher_classroom_subjects',
       as:'teacher_classroom_subjects'

  get 'teachers/:teacher_id/teacher_classroom_subjects/:classroom_id/teacher_grades/:subject_id', to:'teachers#teacher_grades',
       as:'teacher_grades'


  get '/alumns/:id/report', to: 'alumns#report', as: 'alumn_report'

  get '/login_helper', to: 'sessions#login_helper', as: 'login_helper'
  get '/reader/index' , to: 'reader#index'

  namespace :api, defaults: { format: :json } do
    resources :alumns
    resources :strikes
    resources :suspensions
    resources :notifications
    resources :parents
  end


  root 'sessions#new'

  resources :users
  resources :alumns do
    resources :strikes
  end
  resources :strikes
  resources :parents
  resources :notifications
  resources :secretaries
  resources :employees
  resources :teachers
  resources :classrooms
  resources :suspensions
  resources :grades
  resources :subjects
  resources :school_misses
  resources :principal, only: [:show, :edit, :update]
  resources :alumns do
    resources :school_misses
  end

  resources :parents do
    resources :alumns
  end

  resources :alumns do
    resources :suspensions
  end

  resources :classrooms do
    resources :subjects
  end

  resources :classrooms do
    resources :grades
  end
end

app/models/teacher.rb
#File name: teacher.rb
#Class name: Teacher
#Description: Validates teacher's attributes outside single table inheritance
class Teacher < Employee
  has_many :subjects
  before_save :set_password
end

app/controllers/teachers_controller.rb
require 'set'

class TeachersController < ApplicationController

  include SessionsHelper

  def index
    if ( is_employee? )
      @teachers = Teacher.all
    else
        redirect_to "/errors/error_500"
    end
  end

  def show
    if ( is_employee? )
      @teacher = Teacher.find(params[:id])
    else
      redirect_to "/errors/error_500"
    end
  end

  def new
    if ( is_principal? )
      @shifts = Shift.all
      @teacher = Teacher.new
    else
      redirect_to "/errors/error_500"
    end
  end

  def edit
    if ( is_principal? )
      @shifts = Shift.all
      @teacher = Teacher.find(params[:id])
    else
      redirect_to "/errors/error_500"
    end
  end

  def create
    if ( is_principal? )
      @shifts = Shift.all
      @teacher = Teacher.new(teacher_params)
      if (@teacher.save)
        flash[:success] = "Professor(a) criado(a) com sucesso"
        redirect_to users_path
      else
        render 'new'
      end
    else
      redirect_to "/errors/error_500"
    end
  end

  def update
    if ( is_principal? )
      @shifts = Shift.all
      @teacher = Teacher.find(params[:id])
      if ( @teacher.update(teacher_params) )
        flash[:notice] = "Professor(a) alterado(a) com sucesso"
        redirect_to @teacher
      else
        render 'edit'
      end
    else
      redirect_to "/errors/error_500"
    end
  end

  def destroy
    if ( is_principal? )
      @teacher = Teacher.find(params[:id])
      @teacher.destroy
      flash[:alert] = "Professor(a) excluído(a) com sucesso"
      redirect_to users_path
    else
      redirect_to "/errors/error_500"
    end
  end

  def teacher_classrooms
    @subjects = Subject.where("teacher_id = ?", params[:id])
    @classrooms = Set.new
    @subjects.each do |subject|
      relations = ClassroomSubject.where("subject_id = ?", subject.id)
      relations.each do |relation|
        @classrooms.add(Classroom.find_by_id(relation.classroom_id))
      end
    end
  end

  def teacher_classroom_subjects
    @subjects = Subject.where("teacher_id = ?", params[:teacher_id])
    @classroom_subjects = []
    @subjects.each do |subject|
      @classroom_subjects << subject
    end
  end

  def teacher_grades
    @classroom = Classroom.find(params[:classroom_id])
    @subject = Subject.find(params[:subject_id])
    @grades = Grade.where(classroom_id: @classroom.id).where(subject_id: @subject.id)
  end

private
  def teacher_params
    params.require(:teacher).permit(:registry,
                                   :admission_date,
                                   :employee_cpf,
                                   :shift,
                                   :password,
                                   :name,
                                   :address,
                                   :phone,
                                   :gender,
                                   :birth_date,
                                   :admission_date,
                                   :shift_id)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= render "layouts/navbar" %>
<%= form_for (@teacher)  do |f| %>
  <% if @teacher.errors.any? %>
    <div class="container">
      <div class="text-danger text-justify">
        <div id="error_explanation">
          <h2 class=""><%= pluralize(@teacher.errors.count, "erro") %> proibiram este formulario de ser salvo:</h2>
          <ul>
          <% @teacher.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-user"></span>
         Nome
      </span>
      <%= f.text_field :name, class:"form-control", placeholder:"Nome do usuário" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :registry, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-id-card"></span>
        Matricula
      </span>
      <%= f.number_field :registry, class:"form-control", placeholder:"Ex.: 153456" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :employee_cpf, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-id-badge"></span>
        CPF
      </span>
      <%= f.text_field :employee_cpf, class:"form-control", placeholder:"Ex.: 153456" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :classroom_id, class:"sr-only", id: "sel1" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-clock-o"></span>
        Turno
      </span>
      <%= f.select :shift_id, @shifts.collect {|shift| [shift.name_shift, shift.id]}, {:include_blank => false}, {:class => "form-control", :id => "sel1"}%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-home"></span>
         Endereço
      </span>
      <%= f.text_field :address, class:"form-control", placeholder:"Ex.: Rua do limoeiro, casa 53" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-phone"></span>
         Telefone
      </span>
      <%= f.text_field :phone, class:"form-control", placeholder:'Somente números com DDD.' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birth_date, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-gift"></span>
         Data de nascimento
      </span>
      <%= f.date_field :birth_date, class:"form-control", placeholder:"Ex.: dd/mm/aaaa" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :admission_date, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-gift"></span>
         Data de admissão
      </span>
      <%= f.date_field :admission_date, class:"form-control", placeholder:"Ex.: dd/mm/aaaa" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-venus-mars"></span>
         Sexo
      </span>
      <div class="btn-group" data-toggle="buttons">
        <label class="btn btn-radio" name="btn1">
          <%= f.radio_button(:gender,"Feminino") %> Feminino
        </label>
        <label class="btn btn-radio" name="btn2">
          <%= f.radio_button(:gender,"Masculino") %> Masculino
        </label>
      </div>
    </div>
  </div>
  <%= f.button '<span class="fa fa-check"></span> Salvar'.html_safe, type:"submit", class:'btn btn-lg btn-success' %>
<% end %>

app/views/teachers/_form_edit.html.erb
<%= render "layouts/navbar" %>
<%= form_for (@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div class="container">
      <div class="text-danger text-justify">
        <div id="error_explanation">
          <h2 class=""><%= pluralize(@teacher.errors.count, "erro") %> proibiram este formulario de ser salvo:</h2>
          <ul>
          <% @teacher.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-user"></span>
         Nome
      </span>
      <%= f.text_field :name, class:"form-control", placeholder:"Nome do usuário" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :registry, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-id-card"></span>
        Matricula
      </span>
      <%= f.number_field :registry, class:"form-control", placeholder:"Ex.: 153456" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :classroom_id, class:"sr-only", id: "sel1" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-clock-o"></span>
        Turno
      </span>
      <%= f.select :shift_id, @shifts.collect {|shift| [shift.name_shift, shift.id]}, {:include_blank => false}, {:class => "form-control", :id => "sel1"}%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-home"></span>
         Endereço
      </span>
      <%= f.text_field :address, class:"form-control", placeholder:"Ex.: Rua do limoeiro, casa 53" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-phone"></span>
         Telefone
      </span>
      <%= f.text_field :phone, class:"form-control", placeholder:'Somente números com DDD.' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birth_date, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-gift"></span>
         Data de nascimento
      </span>
      <%= f.date_field :birth_date, class:"form-control", placeholder:"Ex.: dd/mm/aaaa" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :admission_date, class:"sr-only" %>
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-gift"></span>
         Data de admissão
      </span>
      <%= f.date_field :admission_date, class:"form-control", placeholder:"Ex.: dd/mm/aaaa" %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
        <span class="fa fa-venus-mars"></span>
         Sexo
      </span>
      <div class="btn-group" data-toggle="buttons">
        <label class="btn btn-radio">
          <%= f.radio_button(:gender,"Feminino") %> Feminino
        </label>
        <label class="btn btn-radio">
          <%= f.radio_button(:gender,"Masculino") %> Masculino
        </label>
      </div>
    </div>
  </div>
  <%= f.submit "Salvar", class:'btn btn-lg btn-success' %>
<% end %>

app/views/teachers/edit.html.erb
<%= render "layouts/navbar" %>
<section class="content-section" id="create">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <h1 class="text-center text-uppercase">
          <span class="fa fa-edit"></span> Alterar Professor
        </h1>
        <%= render 'teachers/form_edit' %>
      </div>
    </div>
  </div>
</section>

app/views/teachers/index.html.erb
<%= render 'layouts/navbar' %>
<section class="content-section" id="alumns-desc">
  <% if flash[:alert]%>
    <br></br>
    <br></br>
   <div class="alert alert-danger" role = "alert"><%= flash[:alert]%></div>
  <% end %>
  <% if flash[:success]%>
   <div class="alert alert-success" role = "alert"><%= flash[:success]%></div>
  <% end %>
  <h1 class="text-uppercase text-center"><span class="fa fa-graduation-cap"></span> Lista de professores</h1>
  <hr></hr>
  <% @teachers.each do |teacher|%>
    <div class="container">
      <div class="row item">
        <div class="col-sm-12 col-md-4">
          <%= image_tag("avatar_250x300.png", alt: "", class: "img-responsive" ) %>
        </div>
        <div class="col-sm-12 col-md-8 text-capitalize descript">
          <% if (teacher.gender == 'Masculino') %>
            <h2>Profº. <%= teacher.name %></h2>
          <% else %>
            <h2>Profª. <%= teacher.name %></h2>
          <% end %>
          <h4>Endereço: <%= teacher.address %> </h4>
          <h4>Data de Aniversário: <%= teacher.birth_date.day %>/<%= teacher.birth_date.month %>/<%= teacher.birth_date.year %> </h4>
          <h4>Sexo: <%= teacher.gender %> </h4>
          <h4>Telefone: <%= teacher.phone %> </h4>
          <h4>Matrícula: <%= teacher.registry %></h4>
          <%= link_to '<span class="fa fa-search-plus"></span> Visualizar'.html_safe, teacher_path(teacher), class:'btn btn-success' %>
          <%= link_to '<span class="fa fa-unlock"></span> Resetar senha'.html_safe, edit_password_employee_path(teacher), class:'btn btn-default' %>
        </div>
      </div>
      <hr>
    </div>
  <% end %>
</section>

app/views/teachers/new.html.erb
<%= render "layouts/navbar" %>
<section class="content-section" id="create">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <h1 class="text-center text-uppercase">
          <span class="fa fa-user-plus"></span> Criar Professor
        </h1>
        <%= render 'teachers/form' %>
      </div>
    </div>
  </div>
</section>

app/views/teachers/show.html.erb
<%= render "layouts/navbar" %>
<br>
<br>
<% if flash[:notice]%>
 <div class="alert alert-warning" role = "alert"><%= flash[:notice]%></div>
<% end %>
<section class="content-section" id="alumns-desc">
  <div class="container">
    <div class="pull-right">
      <%= link_to '<span class="fa fa-user-plus"></span> Visualizar Minhas Turmas'.html_safe, teacher_classrooms_path(@teacher), class:'btn btn-sm btn-success'%>
      <%if @current_user.is_a? (Principal) %>
        <%= link_to '<span class="fa fa-edit"></span> Editar'.html_safe, edit_teacher_path(@teacher), class:"btn btn-sm btn-default" %>
        <%= link_to '<span class="fa fa-times"></span> Excluir'.html_safe, "", method: :delete, class:'btn btn-sm btn-danger', data: { confirm: 'Tem certeza? Essa alteração não pode ser desfeita.' }, name:"delete"  %>
      <%end%>
    </div>
      <div class="row item">
        <div class="col-sm-12 col-md-4">
          <%= image_tag("avatar_250x300.png", alt: "", class: "img-responsive") %>
        </div>
      <div class="col-sm-12 col-md-8 text-capitalize descript">
        <h3>Nome: <%= @teacher.name %></h3>
        <h4>Telefone: <%= @teacher.phone %></h4>
        <h4>Sexo: <%= @teacher.gender %></h4>
        <h4>Endereço: <%= @teacher.address %></h4>
        <h4>Data de Nascimento:  
          <% if(!@teacher.birth_date.nil?)%>
              <%= @teacher.birth_date.strftime("%d/%m/%Y") %>
          <%end%>
        </h4>
        <h4>Data de Admissão: <%= @teacher.admission_date %></h4>
      </div>
    </div>
  </div>
</section>

app/views/teachers/teacher_classroom_subjects.html.erb
<%= render "layouts/navbar" %>
<h1 class="text-uppercase text-center" id="title-list"><span class="fa fa-sticky-note text-left"></span> Matérias</h1>
<hr>
<section class="content-section" >
  <div class="container">
    <% @classroom_subjects.each do |subject| %>
      <div class="row item">
        <div class="col-sm-12 col-md-8 text-capitalize descript">
          <h3>Matéria: <%= subject.name_subject %></h3>
          <h4>Série: <%= subject.class_level %></h4>
          <h4>Professor Responsável: <%= subject.teacher.name %></h4>
          <%= link_to '<span class="fa fa-search-plus"></span> Notas dos Alunos'.html_safe, teacher_grades_path(params[:teacher_id], params[:classroom_id], subject), class:"btn btn-default"%>
        </div>
      </div>
    <%end%>
  </div>
</section>

app/views/teachers/teacher_classrooms.html.erb
<%= render "layouts/navbar" %>
<h1 class="text-uppercase text-center" id="title-list"><span class="glyphicon glyphicon-list text-left"></span> Lista de Turmas</h1>
<hr>
<section class="content-section" id="alumns-desc">
  <% @classrooms.each do |classroom| %>
    <div class="container">
      <div class="pull-right">
        <%if @current_user.is_a?(Teacher) %>
          <%if @current_user.permission=="Teacher" %>
            <%= link_to '<span class="fa fa-address-card"></span> Matérias'.html_safe, teacher_classroom_subjects_path(params[:id], classroom.id), class:'btn btn-sm btn-warning'%>
          <% end %>
        <% end %>
      </div>
      <div class="row item">
        <div class="col-sm-12 col-md-8 descript">
          <h3 class="">Nome da Turma: <%= classroom.name_classroom %></h3>
          <h3 class="">Turno: <%= classroom.shift_classroom %></h3>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</section>

app/views/teachers/teacher_grades.html.erb
<%= render "layouts/navbar" %>
<h1 class="text-uppercase text-center" id="title-list"><span class="glyphicon glyphicon-list text-left"></span> Lista de alunos</h1>
<hr>
<section class="content-section" id="alumns-desc">
  <div class="container">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Nome do Aluno</th>
          <th>Nota do Primeiro Bimestre</th>
          <th>Nota do Segundo Bimestre</th>
          <th>Nota do Terceiro Bimestre</th>
          <th>Nota do Quarto Bimestre</th>
          <th>Nota Final</th>
        </tr>
        <% @grades.each do |grade| %>
        <tr>
          <td align = "center"><%= grade.alumn.name %></td>
          <td align = "center"><%= grade.grade_01 %></td>
          <td align = "center"><%= grade.grade_02 %></td>
          <td align = "center"><%= grade.grade_03 %></td>
          <td align = "center"><%= grade.grade_04 %></td>
          <td align = "center"><%= grade.grade_final %></td>
        </tr>
        <% end %>  
      </thead>
    </table>
  </div>
<hr>
</section>